---
title: "Penguins size comparisons"
author: "Nichoals Bissonnette"
date: "11/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
library(effsize)
library(broom)
library(ggbeeswarm)
library(car)
```

# Part 1. T-tests

mass comparison : male and female chinstrap penguis

```{r}
chinstraps <-penguins %>% 
  filter(species =="Chinstrap")

# Histograms 
ggplot(data=chinstraps, aes(x=body_mass_g)) +
  geom_histogram(bins = 10)+
  facet_wrap(~sex)

## QQ plot 
ggplot(data = chinstraps, aes(sample = body_mass_g))+
  geom_qq() +
  facet_wrap(~sex)

## get descriptive statistics 
chinstraps %>% 
  group_by(sex) %>% 
  summarize(
    mean_mass= mean(body_mass_g),
    median_mass = median(body_mass_g),
    sd_mass= sd(body_mass_g),
    sample_size = n()
  )
```

get vectors of body_mass_g for female and male chinstrap penguins separtely.

```{r}
chinstraps_f <- chinstraps %>% 
  filter(sex== "female") %>% 
  pull(body_mass_g)

chinstraps_m <- chinstraps %>% 
  filter(sex== "male") %>% 
  pull(body_mass_g)
```

### T-tests a couple ways

1. Is ther a significant differce in body mass betwee nmale and female chinstrap penguins?

```{r}
chinstrap_ttest <- t.test(chinstraps_f, chinstraps_m)
chinstrap_ttest

cohen.d(chinstraps_f, chinstraps_m)
```

Are male chinstrap penhiuns significantly larger (body mass) than female chinstrap penguins? 

```{r}
t.test(chinstraps_m,chinstraps_f, alternative = "greater")
```

